using System.ComponentModel.DataAnnotations;
using Ardalis.GuardClauses;

namespace PatientManagerService.Web.ApiModels;

// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
public class PatientDTO : CreatePatientDTO
{
  public PatientDTO(int id, string firstName, string lastName, string birthday, string gender) : base(firstName, lastName, birthday, gender)
  {
    Id = id; //TODO assign guid
    FirstName = firstName;
    LastName = lastName;
    Birthday = birthday;
    Gender = gender;
  }
  public int Id { get; set; }
}

// Creation DTOs should not include an ID if the ID will be generated by the back end
public abstract class CreatePatientDTO
{
  protected CreatePatientDTO(string firstName, string lastName, string birthday, string gender)
  {
    FirstName = firstName;
    LastName = lastName;
    Birthday = birthday;
    Gender = gender;
  }

  [StringLength(35, MinimumLength = 1), Required]
  public string FirstName { get; set; }

  [StringLength(35, MinimumLength = 1), Required]
  public string LastName { get; set; }

  [StringLength(30), Required]
  public string Birthday { get; set; }

  [StringLength(10, MinimumLength = 1), Required]
  public string Gender { get; set; }


}
